### ISSUE TITLE
FB integration: Feasibility

### ISSUE THREAD

**Issue by antmdvs** [juan-rep-max/juan-rep-max#2]
We need [`user_posts` permission](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_posts).

> This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.

Looks a bit discouraging. @benmonro , any experience with this?

**Comment by antmdvs** [comment]
TIL:

> You do not need to submit your app if it will only be used in **Development Mode** by you or someone with a role on your app. Any account listed in the Roles tab in your App Dashboard, such as admins, developers, and testers, can use all permissions but will only be able to access their own data, that of test users, and test pages belonging to them.

https://developers.facebook.com/docs/facebook-login/review/what-is-login-review

---

This permits us to proceed with dev and dev testing in Development Mode. However, the "**limited set of partners**" condition could potentially be a blocker from going to prod.

**Comment by antmdvs** [comment]
- Created a Facebook App (Juan Rep Max) and added your FB user to the Admin role.
- Created 2 test users: 

|Name|Is Authorized for App|Permissions|
|---|:---:|---|
Juan Sepulveda|✔|user_friends, *user_posts*, public_profile|
Bench Monro| ~~No*~~ ✔ |

~~*According to [the docs on `user_posts`](https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_posts), athletes should not need to add the app so long as they tag Juan:~~

> ~~Provides access to the posts on a person's Timeline. Includes their own posts, **posts they are tagged in**, and posts other people make on their Timeline...~~

UPDATE:

> For Posts that tag Users:
>
> * As of April 4th, 2018, apps can no longer read Posts owned by non-app User who have been tagged by an app User. Please refer to the [Breaking Changes changelog](https://developers.facebook.com/docs/graph-api/changelog/breaking-changes/#taggable-friends-4-4) for more details.

Source: https://developers.facebook.com/docs/graph-api/reference/v3.1/post

**Comment by benmonro** [comment]
Ok yeah maybe what we do is require athletes to authorize and/or post them
publicly. Does it work on public posts?

**Comment by antmdvs** [comment]
I searched the docs again, but I don't see any mention of being able to access public posts.

The [public_profile](https://developers.facebook.com/docs/facebook-login/permissions/#reference-default) permission just grants access some basic user fields, but no mention of posts.

**Comment by benmonro** [comment]
Yeah let's just plan on requiring athletes to sign up to participate

**Comment by antmdvs** [comment]
Ok, that will get us by the breaking change referenced in the [update to my above comment](https://github.com/juan-rep-max/juan-rep-max/issues/2#issuecomment-417954765).

Then there's still the "limited set of partners" bit to keep in mind.

**Comment by antmdvs** [comment]
The [inability for test users to comment on posts](https://stackoverflow.com/questions/47176546/facebook-test-users-unable-to-comment-reply-on-page-posts-missing-comment-secti#comment85417136_47176546) is precluding me from proving out the desired process flow in Development Mode.

The [official doc](https://developers.facebook.com/docs/apps/test-users/) reads:

> Test Users can only comment on app Posts published via a Facebook Share Dialog or the Graph API.

so it seems FB is pushing [a paradigm of sharing from apps](https://developers.facebook.com/docs/sharing) which would obviously require athletes to "share" their videos using the app.

That same doc also says:

> Test Users can only interact with other Test Users, **or real Users who have a Admin, Developer, or Tester role on the app**.

I thought this might provide a way to comment using my real user, but so far haven't been able to "interact" in any way with my real user.

That said, I _was_ able to create an [App Page for Juan Rep Max](https://www.facebook.com/Juan-Rep-Max-422987098226344) (unpublished) and post comments on the page's posts, but I know this is not what we want.

We may want to regroup this morning and see what's what.

**Comment by benmonro** [comment]
Can you use you and me as test users?

**Comment by antmdvs** [comment]
Yes. I can retrieve my **public** posts using the app token, but comments on posts return `[]`. Not sure what I'm missing. 🤷‍♂️

**Comment by antmdvs** [comment]
Hold on. JRM is not listed in my active apps:
![image](https://user-images.githubusercontent.com/17127310/45046121-30a1af00-b043-11e8-8a53-a41671eb8c0f.png)

Can you see if you can install it on your account?

**Comment by antmdvs** [comment]
For posterity, here's what I was missing:

## 1. [App tokens](https://developers.facebook.com/docs/facebook-login/access-tokens/#apptokens) are not intended for this type of use:

> App access tokens are used to make requests to Facebook APIs on behalf of an app rather than a user. This can be used to modify the parameters of your app, create and manage test users, or read your apps's insights.
>
> **Limitations**
Some user data that would normally be visible to an app that's making a request with a user access token isn't always visible with an app access token.  **If you're reading user data and using it in your app, you should use a user access token instead of an app access token.** 👈

## 2. Users can only retrieve their own comments

![image](https://user-images.githubusercontent.com/17127310/45256907-eeda7680-b36a-11e8-967b-a2da505d391c.png)

Source: https://developers.facebook.com/docs/graph-api/reference/v3.1/object/comments

This means we **need to use Juan's access token** to check for his "PR LIST" comments.

## 3. [`user_friends`](https://developers.facebook.com/docs/facebook-login/permissions#reference-user_friends) permission

This is needed or the API will not return other users' posts using Juan's access token, *even if he is tagged in them*:

> For Posts that tag Users:
>
> As of April 4th, 2018, apps can no longer read Posts owned by non-app User who have been tagged by an app User. Please refer to the Breaking Changes changelog for more details.

Source: https://developers.facebook.com/docs/graph-api/reference/v3.1/post

---

# Conclusion

Technical Feasibility: ✔
App Review: ❓

Given that all athletes authorize the app with the following permissions:
  * user_friends
  * user_posts

Then we can use Juan's access token to retrieve all his comments on posts for which he was tagged using the `/tagged` "derivative edge" of [`/feed`](https://developers.facebook.com/docs/graph-api/reference/v3.1/user/feed), something like:

https://graph.facebook.com/v3.1/me/tagged/?fields=message,comments
